spring:
  data:
    mongodb:
      uri: mongodb+srv://YOUR_USERNAME:YOUR_PASSWORD@cluster0.gsvdnfz.mongodb.net/SmartCampusDB

  servlet:
    multipart:
      enabled: true
      max-file-size: 5MB
      max-request-size: 5MB

server:
  port: 8080

app:
  frontend:
    url: http://localhost:5173